// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace WebIrcTests
{
    [TestFixture]
    public class VatExceptionCreationTests
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        public static string baseURL;

        [SetUp]
        public void SetUp()
        {
            baseURL = "https://test.irc.ru.dhl.com/calculation";
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void VatExceptionCreationTest()
        {
            OpenHomePage();
            GoToVATExceptionListPage();
            InitRecordCreation();
            FillRecordForm(new VatAccountData("123456789", "123456780"));
            SaveRecordCreation();
            Thread.Sleep(1000);
            GoToHomePage();
        }

        private void GoToHomePage()
        {
            driver.FindElement(By.LinkText("Calculate")).Click();
        }

        private void SaveRecordCreation()
        {
            driver.FindElement(By.XPath("//button[@type=\'button\']")).Click();
            driver.FindElement(By.XPath("//button")).Click();

        }

        private void FillRecordForm(VatAccountData account)
        {
            driver.FindElement(By.Id("account0")).Click();
            driver.FindElement(By.Id("account0")).SendKeys(account.Account0);
            driver.FindElement(By.Id("account20")).Click();
            driver.FindElement(By.Id("account20")).SendKeys(account.Account20);
            driver.FindElement(By.Id("export")).Click();
            driver.FindElement(By.Id("import")).Click();
        }

        private void OpenHomePage()
        {
            driver.Navigate().GoToUrl(baseURL);
        }

        private void GoToVATExceptionListPage()
        {
            driver.FindElement(By.LinkText("Vat Exception List")).Click();
        }

        private void InitRecordCreation()
        {
            driver.FindElement(By.LinkText("Add New Record")).Click();
        }
    }


}
